import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

const interFont = Inter({
  variable: "--font-inter", 
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", 
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`${interFont.variable} ${geistMono.variable} antialiased`}
      >
            {" "}
            {children}
      </body>
    </html>
  );
}
