import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google"; // Import Inter font
import { ScrollShadow } from "@nextui-org/scroll-shadow";
import "@/app/globals.css";

// Replace Geist with Inter for the primary font
const interFont = Inter({
  variable: "--font-inter", // Variable name for Inter font
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Keep Geist Mono as is
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`${interFont.variable} ${geistMono.variable} antialiased`} // Apply Inter font here
      >
            {" "}
            {children}
      </body>
    </html>
  );
}
